apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-depl
  name: payment-depl
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-depl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: payment-depl
    spec:
      containers:
      - image: minhquanvus/app-ui
        imagePullPolicy: IfNotPresent
        name: app-ui
        ports:
            - containerPort: 8081
              protocol: TCP
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
status: {}